version: '3'

services:   
    api:
        container_name: golang-microservice-1
        build: .
        ports: 
            - 5000:5000 
        restart: on-failure
        volumes:
            - api:/usr/src/app/
        depends_on:
            - postgresql-db

        networks:
            - golang-microservice-1-network


    postgresql-db:
        container_name: postgresql-db
        restart: always
        image: postgres:latest
        ports:
            - '5432:5432'
        environment:
            - POSTGRES_USER=${DB_USER}  
            - POSTGRES_PASSWORD=${DB_PASSWORD}
            - POSTGRES_DB=${DB_NAME}
            - DATABASE_HOST=${DB_HOST} 
       
        volumes:
            - database_postgres:/var/lib/postgresql/data

        networks:
            - golang-microservice-1-network
      
volumes:
    api:
    database_postgres: 
        
# Networks to be created to facilitate communication between containers
networks:
    golang-microservice-1-network:
      driver: bridge



        
